repos:
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear]

  - repo: https://github.com/PyCQA/isort
    rev: 5.5.1
    hooks:
      - id: isort
        name: isort
        args:
          - --settings=.

  - repo: https://github.com/PyCQA/pylint
    rev: pylint-2.5.3
    hooks:
      - id: pylint
        name: pylint
        args:
          - --rcfile=.pylintrc
          - --exit-zero
        verbose: true
        additional_dependencies: &pylint_deps
          - pylint-odoo==3.5.0
