name: main

on:
  push:
    branches: [master, legacy]
  pull_request:
    branches: [master, legacy]

env:
  DISABLE_PYTEST_ODOO: 1

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "2.7"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip pre-commit setuptools tox

      - name: Run pre-commit
        run: |
          pre-commit run --all-files

      - name: Run tox tests
        run: |
          tox
