name: publish

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "2.7"

      - name: Install build tools
        run: |
          python -m pip install --upgrade build pip pre-commit setuptools tox twine wheel

      - name: Run pre-commit
        run: |
          pre-commit run --all-files

      - name: Run tox tests
        run: |
          tox

      - name: Build and publish Python package
        env:
          TWINE_REPOSITORY: ${{ secrets.PYPI_REPOSITORY }}
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN_LEGACY }}
        run: |
          python -m build -w
          twine check dist/*
          twine upload dist/*
